{{/* vim: set filetype=mustache: */}}
{{/*
Expand the name of the chart.
*/}}
{{- define "name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" -}}
{{- end -}}

{{- define "image" -}}
{{- if .Values.image.digest -}}
{{ .Values.image.digest | quote }}
{{- else -}}
"{{ .Values.image.repository }}:{{ .Values.image.tag }}"
{{- end -}}
{{- end -}}
