apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    branch: {{ .Values.branch | quote }}
    commit: {{ .Values.commit | quote }}
    owner: {{ .Values.owner | quote }}
    message: {{ .Values.message | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
      annotations:
        branch: {{ .Values.branch | quote }}
        commit: {{ .Values.commit | quote }}
        owner: {{ .Values.owner | quote }}
        message: {{ .Values.message | quote }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.pullSecret }}
      volumes:
        - name: rootdir
          emptyDir: {}
      initContainers:
        - name: install
          image: {{ template "image" . }}
          command:
            - python
            - manage.py
            - warmup
          volumeMounts:
            - name: rootdir
              mountPath: /root
      containers:
        - name: app
          image: {{ template "image" . }}
          command: [ gunicorn, -w, "1", --bind, "0.0.0.0:{{ .Values.ingress.service.port }}",
                     --timeout, "180",
                     --worker-class, "sync",
                     --access-logfile, -,
                     --access-logformat, '%(h)s "%(r)s" %(s)s %(b)s "%(f)s" "%(a)s" %(L)s %({X-Request-ID}i)s',
                     wsgi:application ]
          ports:
            - containerPort: {{ .Values.ingress.service.port }}
          volumeMounts:
            - name: rootdir
              mountPath: /root
          env:
            {{- range $name, $value := .Values.serviceEnv }}
            - name: {{ $name }}
              value: {{ $value | quote }}
            {{- end }}
          resources:
{{ toYaml .Values.resources | indent 12 }}
